### ISSUE TITLE
few PRs

### ISSUE THREAD

**Issue by gilescope** [zcash-hackworks/bn#24]
seems like a lot of people fork and add bits but don't PR back to the main lib?

wondering if there's some way that maybe co-ordination could be improved? I wonder why they don't contribute back...

**Comment by joshuajbouw** [comment]
Not actively maintained at all, unfortunately.

**Comment by daira** [comment]
Correct, this crate is not maintained. I recommend that people switch to either:
* `privacy-scaling-explorations/halo2curves`, which implements the same BN-254 pairing in the [bn256](https://github.com/privacy-scaling-explorations/halo2curves/blob/main/src/bn256) module; or
* [Arkworks](https://github.com/arkworks-rs), which implements the same pairing in the [curves::bn254](https://github.com/arkworks-rs/curves/tree/master/bn254) module.
